import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Display from "./components/Display";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Valorant Skin Theme Picker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="sticky top-0 z-10 w-full p-2 bg-gradient-to-b from-base-100 via-base-100 to-transparent">
          <div className="p-3 shadow-xl rounded-xl bg-base-300">
            <h1 className="text-4xl font-bold">Skin Themes</h1>
          </div>
        </div>
        <Display />
      </main>
    </>
  );
};

export default Home;
