import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Navbar } from "./components/Navbar";
import { Display } from "./components/Skins/Display";

const SkinsPage: NextPage = () => {
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Skins</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navbar />
				<Display weaponUuid={router.query.uuid as string}/>
			</main>
		</>
	);
};

export default SkinsPage;
